### ISSUE TITLE
Porting to latest Sphinx and python3

### ISSUE THREAD

**Issue by oharboe** [ponty/sphinxcontrib-gtkwave#1]
I've hacked up something locally that is starting to work reasonably well with latest Sphinx and Python 3.

Any interest in a pull request?

Some collaboration and help would be required... Lots of guesswork from my side. Read sphinxcontrib.plantuml sourcecode to figure out to make this work.

**Comment by ponty** [comment]
It is a very old project. 
I don't know if Sphinx ineterface has changed meanwhile.
Updating to py3 should be no problem.
Send a PR and I'll check it.
Py27 runs well (Sphinx==1.8.5), I updated the tox.ini.
Just run tox to see it.

**Comment by oharboe** [comment]
> It is a very old project.
> I don't know if Sphinx ineterface has changed meanwhile.
> Updating to py3 should be no problem.
> Send a PR and I'll check it.
> Py27 runs well (Sphinx==1.8.5), I updated the tox.ini.
> Just run tox to see it.

Just a thought. Perhaps it would make sense to make a new "screenshot" sphinx plugin. Being more general the project might attract more contributions.

This "screenshot" sphinx plugin should be easy enough to use and general enough so as to supersede the gtkwave plugin.

**Comment by ponty** [comment]
Is this what you think of?
https://github.com/ponty/sphinxcontrib-programscreenshot

**Comment by oharboe** [comment]
Yes :-)

It too is old though and hasn't seen updates, probably meaning not a lot of users...

What I'm wondering is how one would configurat something like programscreenshot to do what gtkwave does.

I ended up adding more stuff to gtkwave.py that's quite specific to our use-case that I don't know how to express in a configuration file.

**Comment by ponty** [comment]
python3 upgrade is ready.

**Comment by oharboe** [comment]
Thanks!

There a number of changes that I made on top of this, so I can't switch until I file a PR with those changes as well.

I'm closing this issue and I will file a pull request when I have time to make the changes.
